version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: doc/conf.py
  fail_on_warning: true

formats:
  - pdf
  - epub

python:
  install:
    - requirements: requirements-doc.txt
