#! /bin/sh

# This file is part of IVRE.
# Copyright 2011 - 2016 Pierre LALET <pierre.lalet@cea.fr>
#
# IVRE is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# IVRE is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with IVRE. If not, see <http://www.gnu.org/licenses/>.

RELEASE=1
DISTRIB=el6
VERSION=`grep 'version=' setup.py | sed "s#.* version='## ; s#'.*##"`-dev-`git rev-list --count HEAD`.`git rev-parse --short HEAD`
if python --version 2>&1 | grep -q '^Python 2'; then
    PYTHON=python
else
    PYTHON=python2
fi

$PYTHON setup.py bdist_rpm --release=$RELEASE --distribution-name=$DISTRIB --requires=pymongo,python-crypto --obsoletes=IVRE
mv dist/ivre-$VERSION-$RELEASE.noarch.rpm dist/ivre-$VERSION-$RELEASE-$DISTRIB.noarch.rpm
