#! /bin/sh

# This file is part of IVRE.
# Copyright 2011 - 2014 Pierre LALET <pierre.lalet@cea.fr>
#
# IVRE is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# IVRE is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with IVRE. If not, see <http://www.gnu.org/licenses/>.

NMAPOPTS="-vv -A --host-timeout 15m"
NMAPSCRIPTS="(default or discovery or auth) and not (broadcast or brute or \
dos or exploit or external or fuzzer or intrusive)"
SLEEP="sleep 2"
THREADS=10
STOREDOWN="true"

INDIR=./input/
CURDIR=./cur/
OUTDIR=./output/
ERRORDIR=./error/

filter () {
    # This basic filter strips out comments, but one can add here more
    # sophisticaed filters (including network probes). This can be
    # useful to avoid time-consuming honeypots.
    sed 's/ *#.*//'
}

scan () {
    nmap $NMAPOPTS --script="$NMAPSCRIPTS" -iL - -oX -
}

if [ "$TERM" != "screen" ] ; then
    screen "$0" $@
    exit 0
fi

mkdir -p "$INDIR" "$CURDIR" "$OUTDIR" "$ERRORDIR"

if [ -z "$INTHREAD" ] ; then
    screen -X setenv INTHREAD 1
    for i in `seq 2 $THREADS` ; do
	sleep 1
	screen "$0" $@
    done
fi

while true ; do
    [ -f "want_down" ] && break
    fname=`ls -rt "$INDIR" | head -1`
    if [ -z "$fname" ] ; then
	$SLEEP
	continue
    fi
    if ! mv "$INDIR/$fname" "$CURDIR/" ; then
	continue
    fi
    if ! (filter < "$CURDIR/$fname" | scan | bzip2 > "$CURDIR/$fname.xml.bz2") ; then
	mv "$CURDIR/$fname.xml.bz2" "$ERRORDIR/$fname-`date +%s`.xml.bz2"
	cp "$CURDIR/$fname" "$ERRORDIR/$fname-`date +%s`"
	mv "$CURDIR/$fname" "$INDIR/"
	$SLEEP
    else
	if [ "$STOREDOWN" = "true" ] ||
	    bzgrep -q -F '<status state="up"' "$CURDIR/$fname.xml.bz2" ; then
	    mv "$CURDIR/$fname.xml.bz2" "$OUTDIR"
	else
	    rm -f "$CURDIR/$fname.xml.bz2"
	fi
	rm -f "$CURDIR/$fname"
    fi
done
