#! /bin/sh

# This file is part of IVRE.
# Copyright 2011 - 2021 Pierre LALET <pierre@droids-corp.org>
#
# IVRE is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# IVRE is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with IVRE. If not, see <http://www.gnu.org/licenses/>.

cd `dirname $0`/../docker
docker pull debian:stable
docker pull debian:buster
for img in base client agent db web web-apache ; do
    docker build --no-cache -t "ivre/$img" "$img" || break
done

# Uncomment to push images
# docker login
# for img in base client agent db web web-apache ; do
#     docker push "ivre/$img"
# done
