# This file is part of IVRE.
# Copyright 2011 - 2026 Pierre LALET <pierre@droids-corp.org>
#
# IVRE is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# IVRE is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with IVRE. If not, see <http://www.gnu.org/licenses/>.

name: Package builds

on: [push, pull_request]

# https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/control-the-concurrency-of-workflows-and-jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'master')}}

jobs:
  arch:
    runs-on: ubuntu-24.04
    container: archlinux:latest
    steps:

    - name: Install dependencies
      run: pacman -Syu --noconfirm base-devel git python python-build python-installer python-setuptools python-setuptools-scm

    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Build packages
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        git checkout -B ci-build
        useradd -m builder
        echo 'builder ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
        chown -R builder:builder .
        su builder -c 'cd pkg/arch/ivre && makepkg -sf --noconfirm'
